// apps/solid-demo/src/app.tsx
import { Router } from "@solidjs/router";
import { FileRoutes } from "@solidjs/start/router";
import { Suspense } from "solid-js";
import { MetaProvider } from "@solidjs/meta";
import { Ssgoi, type SsgoiConfig } from "@ssgoi/solid";
import { fade, hero } from "@ssgoi/solid/view-transitions";
import "./app.css";

const ssgoiConfig: SsgoiConfig = {
  transitions: [
    // Use hero transition between main and item detail pages
    {
      from: "/",
      to: "/item/*",
      transition: hero({ spring: { stiffness: 5, damping: 1 } }),
      symmetric: true,
    },
  ],
};

export default function App() {
  return (
    <Router
      root={(props) => (
        <MetaProvider>
          <Ssgoi config={ssgoiConfig}>
            <div
              style={{
                position: "relative",
                "min-height": "100vh",
                width: "100%",
              }}
            >
              <Suspense>{props.children}</Suspense>
            </div>
          </Ssgoi>
        </MetaProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}

// apps/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Ssgoi } from '@ssgoi/angular';
import { fade, hero, jaemin } from '@ssgoi/angular/view-transitions';
import type { SsgoiConfig } from '@ssgoi/angular';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, Ssgoi],
  template: `
    <ssgoi [config]="ssgoiConfig">
      <div style="position: relative; min-height: 100vh; width: 100%">
        <router-outlet />
      </div>
    </ssgoi>
  `,
  styles: [],
})
export class AppComponent {
  ssgoiConfig: SsgoiConfig = {
    transitions: [
      {
        from: '/',
        to: '/item/*',
        transition: hero({ spring: { stiffness: 5, damping: 1 } }),
        symmetric: true,
      },
      {
        from: '/',
        to: '/jaemin',
        transition: jaemin(),
      },
      {
        from: '/jaemin',
        to: '/',
        transition: fade(),
      },
    ],
  };
}
