// apps/vue-demo/app/app.vue
<template>
  <Ssgoi :config="ssgoiConfig">
    <div style="position: relative; min-height: 100vh; width: 100%">
      <NuxtPage />
    </div>
  </Ssgoi>
</template>

<script setup lang="ts">
import { Ssgoi } from '@ssgoi/vue';
import { hero } from '@ssgoi/vue/view-transitions';
import type { SsgoiConfig } from '@ssgoi/vue';

const ssgoiConfig: SsgoiConfig = {
  transitions: [
    // Use hero transition between main and item detail pages
    {
      from: '/',
      to: '/item/*',
      transition: hero({ spring: { stiffness: 5, damping: 1 } }),
      symmetric: true,
    },
  ],
};
</script>

// apps/solid-demo/src/app.tsx
import { Router } from "@solidjs/router";
import { FileRoutes } from "@solidjs/start/router";
import { Suspense } from "solid-js";
import { MetaProvider } from "@solidjs/meta";
import { Ssgoi, type SsgoiConfig } from "@ssgoi/solid";
import { fade, hero } from "@ssgoi/solid/view-transitions";
import "./app.css";

const ssgoiConfig: SsgoiConfig = {
  transitions: [
    // Use hero transition between main and item detail pages
    {
      from: "/",
      to: "/item/*",
      transition: hero({ spring: { stiffness: 5, damping: 1 } }),
      symmetric: true,
    },
  ],
};

export default function App() {
  return (
    <Router
      root={(props) => (
        <MetaProvider>
          <Ssgoi config={ssgoiConfig}>
            <div
              style={{
                position: "relative",
                "min-height": "100vh",
                width: "100%",
              }}
            >
              <Suspense>{props.children}</Suspense>
            </div>
          </Ssgoi>
        </MetaProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}
