// apps/docs/src/components/layout/header.tsx
"use client";

import Link from "next/link";
import { cn } from "@/lib/utils";
import { Menu, Github } from "lucide-react";
import { useState } from "react";
import { messages } from "@/messages";
import { MobileDrawer } from "./mobile-drawer";
import { usePathname } from "next/navigation";
import Image from "next/image";

export function Header() {
  const [mobileDrawerOpen, setMobileDrawerOpen] = useState(false);
  const pathname = usePathname();

  const isActive = (path: string) => {
    return pathname === path || (path !== "/" && pathname.startsWith(path));
  };

  return (
    <>
      {/* Mobile Header - Center floating */}
      <header className="md:hidden fixed top-4 left-1/2 -translate-x-1/2 z-50">
        <div className="px-4 py-2 rounded-full bg-neutral-900/70 backdrop-blur-md border border-white/10">
          <Link href={`/`} className="flex items-center gap-2">
            <Image
              src="/ssgoi-logo.png"
              alt="SSGOI Logo"
              width={24}
              height={24}
              className="h-6 w-6 rounded-full object-cover"
            />
            <span className="text-sm font-medium tracking-tight">SSGOI</span>
          </Link>
        </div>
      </header>

      {/* Mobile Menu Button */}
      <button
        className="md:hidden fixed top-4 right-4 z-50 h-9 w-9 flex items-center justify-center rounded-full bg-neutral-900/70 backdrop-blur-md border border-white/10 text-neutral-300 hover:text-white transition-colors"
        onClick={() => setMobileDrawerOpen(!mobileDrawerOpen)}
      >
        <Menu className="h-4 w-4" />
        <span className="sr-only">{messages.header.openMenu}</span>
      </button>

      {/* Desktop Header - Center floating */}
      <header className="hidden md:flex justify-center fixed w-[660px]  top-4 left-1/2 -translate-x-1/2 z-50 px-2 py-2 rounded-full bg-neutral-900/70 backdrop-blur-md border border-white/10">
        <div className="flex items-center gap-2 px-2">
          {/* Logo */}
          <Link href={`/`} className="flex items-center gap-2 shrink-0">
            <Image
              src="/ssgoi-logo.png"
              alt="SSGOI Logo"
              width={24}
              height={24}
              className="h-6 w-6 rounded-full object-cover"
            />
            <span className="text-sm font-medium tracking-tight">SSGOI</span>
          </Link>

          {/* Navigation */}
          <nav className="flex items-center gap-0.5">
            <Link
              href={`/docs`}
              className={cn(
                "px-3 py-1.5 text-xs rounded-full transition-colors",
                isActive(`/docs`)
                  ? "bg-white/10 text-white"
                  : "text-neutral-300 hover:text-white",
              )}
            >
              {messages.header.docs}
            </Link>
            <Link
              href={`/blog`}
              className={cn(
                "px-3 py-1.5 text-xs rounded-full transition-colors",
                isActive(`/blog`)
                  ? "bg-white/10 text-white"
                  : "text-neutral-300 hover:text-white",
              )}
            >
              {messages.header.blog}
            </Link>
            <Link
              href={`/demo`}
              className={cn(
                "px-3 py-1.5 text-xs rounded-full transition-colors",
                isActive(`/demo`)
                  ? "bg-white/10 text-white"
                  : "text-neutral-300 hover:text-white",
              )}
            >
              {messages.header.demo}
            </Link>
            <Link
              href={`/showcase`}
              className={cn(
                "px-3 py-1.5 text-xs rounded-full transition-colors",
                isActive(`/showcase`)
                  ? "bg-white/10 text-white"
                  : "text-neutral-300 hover:text-white",
              )}
            >
              {messages.header.showcase}
            </Link>
          </nav>

          {/* Separator */}
          <div className="w-px h-4 bg-white/10" />

          {/* Right Actions */}
          <div className="flex items-center gap-1">
            {/* Discord */}
            <Link
              href="https://discord.gg/9gSSWQbvX4"
              target="_blank"
              rel="noopener noreferrer"
              className="h-7 w-7 flex items-center justify-center rounded-full text-neutral-300 hover:text-white hover:bg-white/5 transition-colors"
              aria-label="Discord"
            >
              <svg
                viewBox="0 0 24 24"
                className="h-3.5 w-3.5 fill-current"
                aria-hidden="true"
              >
                <path d="M19.27 5.33C17.94 4.71 16.5 4.26 15 4a.09.09 0 0 0-.07.03c-.18.33-.39.76-.53 1.09a16.09 16.09 0 0 0-4.8 0c-.14-.34-.35-.76-.54-1.09-.01-.02-.04-.03-.07-.03-1.5.26-2.93.71-4.27 1.33-.01 0-.02.01-.03.02-2.72 4.07-3.47 8.03-3.1 11.95 0 .02.01.04.03.05 1.8 1.32 3.53 2.12 5.24 2.65.03.01.06 0 .07-.02.4-.55.76-1.13 1.07-1.74.02-.04 0-.08-.04-.09-.57-.22-1.11-.48-1.64-.78-.04-.02-.04-.08-.01-.11.11-.08.22-.17.33-.25.02-.02.05-.02.07-.01 3.44 1.57 7.15 1.57 10.55 0 .02-.01.05-.01.07.01.11.09.22.17.33.26.04.03.04.09-.01.11-.52.31-1.07.56-1.64.78-.04.01-.05.06-.04.09.32.61.68 1.19 1.07 1.74.03.01.06.02.09.01 1.72-.53 3.45-1.33 5.25-2.65.02-.01.03-.03.03-.05.44-4.53-.73-8.46-3.1-11.95-.01-.01-.02-.02-.04-.02zM8.52 14.91c-1.03 0-1.89-.95-1.89-2.12s.84-2.12 1.89-2.12c1.06 0 1.9.96 1.89 2.12 0 1.17-.84 2.12-1.89 2.12zm6.97 0c-1.03 0-1.89-.95-1.89-2.12s.84-2.12 1.89-2.12c1.06 0 1.9.96 1.89 2.12 0 1.17-.83 2.12-1.89 2.12z" />
              </svg>
            </Link>

            {/* X (Twitter) */}
            <Link
              href="https://x.com/meursyphus"
              target="_blank"
              rel="noopener noreferrer"
              className="h-7 w-7 flex items-center justify-center rounded-full text-neutral-300 hover:text-white hover:bg-white/5 transition-colors"
              aria-label="X (Twitter)"
            >
              <svg
                viewBox="0 0 24 24"
                className="h-3.5 w-3.5 fill-current"
                aria-hidden="true"
              >
                <path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z" />
              </svg>
            </Link>

            {/* GitHub */}
            <Link
              href="https://github.com/meursyphus/ssgoi"
              target="_blank"
              rel="noopener noreferrer"
              className="h-7 w-7 flex items-center justify-center rounded-full text-neutral-300 hover:text-white hover:bg-white/5 transition-colors"
              aria-label={messages.header.githubRepository}
            >
              <Github className="h-3.5 w-3.5" />
            </Link>
          </div>
        </div>
      </header>

      <MobileDrawer
        isOpen={mobileDrawerOpen}
        onClose={() => setMobileDrawerOpen(false)}
      />
    </>
  );
}

// packages/docs/src/routes/(app)/header.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { theme, toggleTheme } from '$lib/theme';
	import { Moon, Sun } from 'lucide-svelte';

	let isMenuOpen = false;

	function toggleMenu() {
		isMenuOpen = !isMenuOpen;
	}
</script>

<header>
	<div class="header-content">
		<a href="/" class="logo">
			<img src="/icon.svg" alt="SSGOI" />
			<span>SSGOI</span>
		</a>
		<nav class:open={isMenuOpen}>
			<a href="/docs" class:active={$page.url.pathname.startsWith('/docs')}>Docs</a>
			<a href="/demo" rel="noopener noreferrer" target="_blank">Demo</a>
			<a href="https://github.com/meursyphus/ssgoi">
				<a href="https://github.com/meursyphus/ssgoi" aria-label="GitHub">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 24 24"
						width="24"
						height="24"
						fill="currentColor"
						class="github-icon"
					>
						<path
							d="M12 .297c-6.627 0-12 5.373-12 12 0 5.304 3.438 9.8 8.205 11.388.6.111.82-.26.82-.577 0-.285-.011-1.237-.017-2.24-3.338.724-4.043-1.607-4.043-1.607-.546-1.384-1.333-1.754-1.333-1.754-1.086-.743.083-.728.083-.728 1.204.085 1.838 1.236 1.838 1.236 1.067 1.826 2.8 1.298 3.48.992.108-.774.418-1.298.76-1.598-2.665-.303-5.467-1.333-5.467-5.933 0-1.313.469-2.386 1.236-3.227-.124-.303-.536-1.53.117-3.185 0 0 1.008-.322 3.303 1.227a11.53 11.53 0 0 1 3.003-.404c1.02.004 2.042.138 3.003.404 2.295-1.55 3.303-1.227 3.303-1.227.653 1.655.241 2.882.118 3.185.77.841 1.236 1.914 1.236 3.227 0 4.61-2.805 5.63-5.475 5.925.43.37.815 1.1.815 2.22 0 1.604-.014 2.898-.017 3.287 0 .319.218.694.825.577A12.002 12.002 0 0 0 24 12.297c0-6.627-5.373-12-12-12z"
						/>
					</svg>
				</a>
			</a>
			<button on:click={toggleTheme} aria-label="Toggle theme">
				{#if $theme === 'light'}
					<Moon size={20} />
				{:else}
					<Sun size={20} />
				{/if}
			</button>
		</nav>
		<button class="menu-toggle" on:click={toggleMenu} aria-label="Toggle menu">
			<span></span>
			<span></span>
			<span></span>
		</button>
	</div>
</header>

<style>
	header {
		background-color: var(--color-bg-light);
		box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
		position: sticky;
		top: 0;
		z-index: 1000;
		transition: background-color 0.3s;
	}

	.header-content {
		max-width: 1200px;
		margin: 0 auto;
		display: flex;
		justify-content: space-between;
		align-items: center;
		padding: var(--spacing-4);
	}

	.logo {
		font-size: var(--font-size-xl);
		font-weight: bold;
		color: var(--color-primary-light);
		text-decoration: none;
		transition: color 0.3s;
		display: flex;
		align-items: center;
		gap: var(--spacing-2);
	}

	.logo img {
		width: 32px;
		height: 32px;
	}

	nav {
		display: flex;
		gap: var(--spacing-4);
		align-items: center;
	}

	nav a {
		color: var(--color-text-light);
		text-decoration: none;
		transition: color 0.3s;
	}

	nav a:hover,
	nav a.active {
		color: var(--color-primary-light);
	}

	button {
		background: none;
		border: none;
		cursor: pointer;
		color: var(--color-text-light);
		transition: color 0.3s;
	}

	button:hover {
		color: var(--color-primary-light);
	}

	.menu-toggle {
		display: none;
	}

	/* Dark mode styles */
	:global(html[color-scheme='dark']) header {
		background-color: var(--color-bg-dark);
		box-shadow: 0 2px 4px rgba(255, 255, 255, 0.1);
	}

	:global(html[color-scheme='dark']) .logo {
		color: var(--color-primary-dark);
	}

	:global(html[color-scheme='dark']) nav a {
		color: var(--color-text-dark);
	}

	:global(html[color-scheme='dark']) nav a:hover,
	:global(html[color-scheme='dark']) nav a.active {
		color: var(--color-primary-dark);
	}

	:global(html[color-scheme='dark']) button {
		color: var(--color-text-dark);
	}

	:global(html[color-scheme='dark']) button:hover {
		color: var(--color-primary-dark);
	}

	@media (max-width: 768px) {
		nav {
			display: none;
		}

		nav.open {
			display: flex;
			flex-direction: column;
			position: absolute;
			top: 100%;
			left: 0;
			right: 0;
			background-color: var(--color-bg-light);
			padding: var(--spacing-4);
			box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
		}

		.menu-toggle {
			display: block;
		}

		.menu-toggle span {
			display: block;
			width: 25px;
			height: 3px;
			background-color: var(--color-text-light);
			margin: 5px 0;
			transition: 0.3s;
		}

		:global(html[color-scheme='dark']) nav.open {
			background-color: var(--color-bg-dark);
			box-shadow: 0 4px 6px rgba(255, 255, 255, 0.1);
		}

		:global(html[color-scheme='dark']) .menu-toggle span {
			background-color: var(--color-text-dark);
		}
	}
</style>
