// templates/react-router/app/components/ssgoi-transition-boundary.tsx
import { type ElementType, type ReactNode } from "react";
import { useLocation } from "react-router";

export function SsgoiTransitionBoundary({
  children,
  as,
  className,
}: {
  children: ReactNode;
  as?: ElementType;
  className?: string;
}) {
  const { pathname } = useLocation();
  const Component = as ?? "div";

  return (
    <Component
      key={pathname}
      data-ssgoi-transition={pathname}
      className={className}
    >
      {children}
    </Component>
  );
}

// templates/solidstart/src/components/ssgoi-transition-boundary.tsx
import { useLocation } from "@solidjs/router";
import { Show, splitProps, type JSX } from "solid-js";

type Props = JSX.HTMLAttributes<HTMLDivElement> & {
  children?: JSX.Element;
  getId?: (pathname: string) => string;
};

const pathnameId = (pathname: string) => pathname;

export function SsgoiTransitionBoundary(props: Props) {
  const location = useLocation();
  const [local, rest] = splitProps(props, ["children", "getId"]);
  const transitionId = () => (local.getId ?? pathnameId)(location.pathname);

  return (
    <Show when={transitionId()} keyed>
      {(id) => (
        <div {...rest} data-ssgoi-transition={id}>
          {local.children}
        </div>
      )}
    </Show>
  );
}
