// packages/solid/src/lib/routers/solid-router.tsx
import { useLocation } from "@solidjs/router";
import { createMemo, Show, splitProps, type JSX } from "solid-js";
import { Dynamic } from "solid-js/web";

export interface RouteBoundaryState {
  id: string;
  key?: string | number;
}

export type SsgoiRouteBoundaryProps = JSX.HTMLAttributes<HTMLElement> & {
  as?: keyof JSX.IntrinsicElements;
  routeKey?: string | number;
  resolve?: (location: { pathname: string }) => RouteBoundaryState;
};

/** @experimental Solid Router integration, including SolidStart. The API may change. */
export function SsgoiRouteBoundary(props: SsgoiRouteBoundaryProps) {
  const location = useLocation();
  const [local, rest] = splitProps(props, [
    "children",
    "as",
    "resolve",
    "routeKey",
  ]);
  const boundary = createMemo(
    () =>
      local.resolve?.({ pathname: location.pathname }) ?? {
        id: location.pathname,
      },
  );
  // Show uses truthiness. A token also supports valid keys such as 0 and "".
  const lifetime = createMemo<{ key: string | number }>((previous) => {
    const current = boundary();
    const key = local.routeKey ?? current.key ?? current.id;
    return previous?.key === key ? previous : { key };
  });

  return (
    <Show when={lifetime()} keyed>
      {(_lifetime) => (
        <Dynamic
          component={local.as ?? "div"}
          {...rest}
          data-ssgoi-transition={boundary().id}
        >
          {local.children}
        </Dynamic>
      )}
    </Show>
  );
}

// packages/react/src/routers/react-router.tsx
"use client";

import type { ElementType } from "react";
import { useLocation, type Location } from "react-router";
import { RouteBoundary, type RouteBoundaryProps } from "./route-boundary";

export type SsgoiRouteBoundaryProps<T extends ElementType = "div"> =
  RouteBoundaryProps<Location, T>;

/** @experimental React Router integration. The API may change. */
export function SsgoiRouteBoundary<T extends ElementType = "div">({
  resolve,
  ...props
}: SsgoiRouteBoundaryProps<T>) {
  const location = useLocation();
  const boundary = resolve?.(location) ?? { id: location.pathname };
  return <RouteBoundary {...props} boundary={boundary} />;
}

export type { RouteBoundaryState } from "./route-boundary";
