// templates/solidstart/src/components/products.tsx
import { For, Show } from "solid-js";
import { getProductsByCategory, type Product } from "../data/products";

export function ProductGrid(props: { category: string }) {
  const products = () => getProductsByCategory(props.category);
  const transitionId = () => `/products/${props.category}`;

  return (
    <div data-ssgoi-transition={transitionId()}>
      <div class="px-4 pb-6 h-full overflow-y-auto">
        <Show
          when={products().length > 0}
          fallback={
            <div class="text-center py-12">
              <p class="text-neutral-500 text-sm">
                No products in this category
              </p>
            </div>
          }
        >
          <div class="grid grid-cols-2 gap-3">
            <For each={products()}>
              {(product) => <ProductCard product={product} />}
            </For>
          </div>
        </Show>
      </div>
    </div>
  );
}

function ProductCard(props: { product: Product }) {
  const badgeClass = () => {
    if (props.product.badge === "sale") return "bg-red-500/90 text-white";
    if (props.product.badge === "new") return "bg-blue-500/90 text-white";
    return "bg-amber-500/90 text-black";
  };

  return (
    <div class="block bg-white/5 rounded-xl overflow-hidden">
      <div class="relative aspect-square overflow-hidden">
        <img
          src={props.product.image}
          alt={props.product.name}
          class="w-full h-full object-cover"
        />
        <Show when={props.product.badge}>
          {(badge) => (
            <span
              class={`absolute top-2 left-2 px-2 py-0.5 rounded text-[10px] font-medium uppercase ${badgeClass()}`}
            >
              {badge()}
            </span>
          )}
        </Show>
      </div>

      <div class="p-3">
        <span class="text-[10px] text-neutral-500 uppercase tracking-wide">
          {props.product.category}
        </span>
        <h3 class="text-xs font-medium text-white mt-0.5 line-clamp-2 leading-tight">
          {props.product.name}
        </h3>
        <div class="flex items-baseline gap-1.5 mt-2">
          <span class="text-sm font-semibold text-white">
            ${props.product.price}
          </span>
          <Show when={props.product.originalPrice}>
            {(originalPrice) => (
              <span class="text-[10px] text-neutral-500 line-through">
                ${originalPrice()}
              </span>
            )}
          </Show>
        </div>
        <div class="flex items-center gap-1 mt-1.5 text-[10px] text-neutral-400">
          <span class="text-amber-400">*</span>
          <span>{props.product.rating}</span>
          <span class="text-neutral-600">/</span>
          <span>{props.product.reviews} reviews</span>
        </div>
      </div>
    </div>
  );
}

// apps/docs/src/components/demo/products/index.tsx
"use client";

import React from "react";
import { products } from "./mock-data";
import { SsgoiTransition } from "@meursyphus/ssgoi-react";

export default function ProductsDemo() {
  return (
    <SsgoiTransition id="/demo/products">
      <div className="min-h-screen bg-gray-950 px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Shop</h1>
          <p className="text-gray-400">Discover our curated collection</p>
        </div>

        {/* Products Grid */}
        <div className="grid grid-cols-2 gap-4">
          {products.map((product) => (
            <article
              key={product.id}
              className="bg-gray-900 rounded-xl overflow-hidden transition-all duration-200 hover:transform hover:-translate-y-1 hover:shadow-xl border border-gray-800"
            >
              {/* Product Image */}
              <div className="relative aspect-square">
                <img
                  src={product.image}
                  alt={product.name}
                  className="w-full h-full object-cover bg-gray-800"
                />
                {product.badge && (
                  <span
                    className={`absolute top-3 left-3 px-2 py-1 rounded text-xs font-semibold uppercase ${
                      product.badge === 'new'
                        ? 'bg-teal-500 text-white'
                        : product.badge === 'sale'
                        ? 'bg-red-500 text-white'
                        : 'bg-yellow-400 text-gray-900'
                    }`}
                  >
                    {product.badge}
                  </span>
                )}
              </div>

              {/* Product Info */}
              <div className="p-3 sm:p-4">
                <span className="text-xs text-gray-500 uppercase tracking-wider">
                  {product.category}
                </span>
                <h3 className="text-sm sm:text-base font-semibold text-white mt-1 mb-2 line-clamp-2">
                  {product.name}
                </h3>
                
                <p className="hidden sm:block text-xs text-gray-400 line-clamp-2 mb-3">
                  {product.description}
                </p>

                {/* Rating */}
                <div className="flex items-center gap-1 text-xs mb-3">
                  <span className="text-yellow-400">★★★★★</span>
                  <span className="font-semibold text-white">
                    {product.rating}
                  </span>
                  <span className="text-gray-500">({product.reviews})</span>
                </div>

                {/* Price Section */}
                <div className="flex justify-between items-center">
                  <div className="flex items-baseline gap-2">
                    <span className="text-lg font-bold text-white">
                      ${product.price}
                    </span>
                    {product.originalPrice && (
                      <span className="text-sm text-gray-500 line-through">
                        ${product.originalPrice}
                      </span>
                    )}
                  </div>
                  {!product.inStock && (
                    <span className="text-xs text-gray-500 font-medium">
                      Out of stock
                    </span>
                  )}
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </SsgoiTransition>
  );
}
