// templates/nuxt/components/ssgoi-transition-boundary.vue
<template>
  <component :is="as" :key="transitionId" :data-ssgoi-transition="transitionId">
    <slot />
  </component>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useRoute } from "vue-router";

interface Props {
  as?: keyof HTMLElementTagNameMap;
  getId?: (pathname: string) => string;
}

const props = withDefaults(defineProps<Props>(), {
  as: "div",
  getId: (pathname: string) => pathname,
});

const route = useRoute();
const transitionId = computed(() => props.getId(route.path));
</script>

// templates/react-router/app/components/ssgoi-transition-boundary.tsx
import { type ElementType, type ReactNode } from "react";
import { useLocation } from "react-router";

export function SsgoiTransitionBoundary({
  children,
  as,
  className,
}: {
  children: ReactNode;
  as?: ElementType;
  className?: string;
}) {
  const { pathname } = useLocation();
  const Component = as ?? "div";

  return (
    <Component
      key={pathname}
      data-ssgoi-transition={pathname}
      className={className}
    >
      {children}
    </Component>
  );
}
