// apps/solid-demo/src/routes/index.tsx
import { createSignal } from "solid-js";
import { A } from "@solidjs/router";
import { SsgoiTransition, transition, TransitionScope } from "@ssgoi/solid";

const colors = [
  { id: 1, color: "#FF6B6B", name: "Coral" },
  { id: 2, color: "#4ECDC4", name: "Turquoise" },
  { id: 3, color: "#45B7D1", name: "Sky Blue" },
  { id: 4, color: "#96CEB4", name: "Sage" },
  { id: 5, color: "#FECA57", name: "Sunflower" },
  { id: 6, color: "#DDA0DD", name: "Plum" },
];

export default function Home() {
  const [showShapes, setShowShapes] = createSignal(true);
  const [stiffness, setStiffness] = createSignal(300);
  const [damping, setDamping] = createSignal(30);

  // TransitionScope demo states
  const [showScopeContainer, setShowScopeContainer] = createSignal(true);
  const [showLocalChild, setShowLocalChild] = createSignal(true);
  const [showGlobalChild, setShowGlobalChild] = createSignal(true);

  return (
    <SsgoiTransition id="/">
      <div class="max-w-[1200px] mx-auto p-8">
        <div class="text-center py-12 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl mb-12 shadow-xl">
          <h1 class="text-5xl md:text-4xl font-bold text-white drop-shadow-md">
            SSGOI Solid Demo
          </h1>
        </div>

        {/* Hero Transition Section */}
        <div class="mb-16 p-8 bg-neutral-800 rounded-xl shadow-lg">
          <h2 class="text-3xl font-semibold mb-8 text-gray-100 border-b-2 border-neutral-600 pb-2">
            Hero Transition
          </h2>
          <div class="grid grid-cols-[repeat(auto-fill,minmax(150px,1fr))] md:grid-cols-[repeat(auto-fill,minmax(120px,1fr))] gap-6 md:gap-4 mb-8">
            {colors.map((item) => (
              <A
                href={`/item/${item.id}`}
                class="aspect-square rounded-xl flex items-center justify-center cursor-pointer shadow-lg hover:shadow-xl no-underline"
                style={{ "background-color": item.color }}
                data-hero-key={`color-${item.id}`}
              >
                <span class="text-lg font-semibold text-white drop-shadow-md">
                  {item.name}
                </span>
              </A>
            ))}
          </div>
        </div>

        {/* DOM Transition Section */}
        <div class="mb-8 p-8 bg-neutral-800 rounded-xl shadow-lg">
          <div class="flex flex-col gap-6 md:gap-4">
            <div class="flex gap-4 justify-center">
              <button
                class={`px-8 py-3 border-2 rounded-lg cursor-pointer font-semibold transition-all duration-200 hover:-translate-y-0.5 ${
                  stiffness() === 100
                    ? "border-purple-600 text-white shadow-lg"
                    : "border-neutral-600 bg-neutral-700 text-gray-100 hover:bg-neutral-600"
                }`}
                style={
                  stiffness() === 100
                    ? {
                        background:
                          "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                      }
                    : {}
                }
                onClick={() => {
                  setStiffness(100);
                  setDamping(20);
                }}
              >
                Smooth
              </button>
              <button
                class={`px-8 py-3 border-2 rounded-lg cursor-pointer font-semibold transition-all duration-200 hover:-translate-y-0.5 ${
                  stiffness() === 300
                    ? "border-purple-600 text-white shadow-lg"
                    : "border-neutral-600 bg-neutral-700 text-gray-100 hover:bg-neutral-600"
                }`}
                style={
                  stiffness() === 300
                    ? {
                        background:
                          "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                      }
                    : {}
                }
                onClick={() => {
                  setStiffness(300);
                  setDamping(30);
                }}
              >
                Normal
              </button>
              <button
                class={`px-8 py-3 border-2 rounded-lg cursor-pointer font-semibold transition-all duration-200 hover:-translate-y-0.5 ${
                  stiffness() === 500
                    ? "border-purple-600 text-white shadow-lg"
                    : "border-neutral-600 bg-neutral-700 text-gray-100 hover:bg-neutral-600"
                }`}
                style={
                  stiffness() === 500
                    ? {
                        background:
                          "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                      }
                    : {}
                }
                onClick={() => {
                  setStiffness(500);
                  setDamping(40);
                }}
              >
                Fast
              </button>
            </div>

            <div class="flex items-center justify-center gap-4 md:flex-col md:items-stretch">
              <label class="font-semibold text-gray-100 min-w-[100px]">
                Stiffness
              </label>
              <input
                type="number"
                class="p-2 border-2 border-neutral-600 rounded-md w-[120px] text-base bg-neutral-700 text-gray-100"
                value={stiffness()}
                onInput={(e) => setStiffness(Number(e.currentTarget.value))}
                min="1"
                max="1000"
              />
              <span class="text-gray-400 text-sm">(1-1000)</span>
            </div>

            <div class="flex items-center justify-center gap-4 md:flex-col md:items-stretch">
              <label class="font-semibold text-gray-100 min-w-[100px]">
                Damping
              </label>
              <input
                type="number"
                class="p-2 border-2 border-neutral-600 rounded-md w-[120px] text-base bg-neutral-700 text-gray-100"
                value={damping()}
                onInput={(e) => setDamping(Number(e.currentTarget.value))}
                min="0"
                max="100"
              />
              <span class="text-gray-400 text-sm">(0-100)</span>
            </div>
          </div>
        </div>

        <div class="text-center mb-8">
          <button
            onClick={() => setShowShapes(!showShapes())}
            class="px-10 py-4 text-white border-none rounded-lg text-lg font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[0_6px_24px_rgba(102,126,234,0.6)] disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_4px_16px_rgba(102,126,234,0.4)]"
            style={{
              background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
            }}
          >
            {showShapes() ? "Hide Elements" : "Show Elements"}
          </button>
        </div>

        <div class="p-8 bg-neutral-800 rounded-xl shadow-lg">
          <h2 class="text-3xl font-semibold mb-8 text-gray-100 border-b-2 border-neutral-600 pb-2">
            DOM Transition
          </h2>
          <div class="grid grid-cols-[repeat(auto-fill,minmax(200px,1fr))] md:grid-cols-[repeat(auto-fill,minmax(150px,1fr))] gap-8 md:gap-6 justify-items-center">
            {/* Fade */}
            <div class="flex flex-col items-center gap-4">
              <div class="w-[120px] h-[120px] flex items-center justify-center">
                {showShapes() && (
                  <div
                    ref={transition({
                      key: "fade",
                      in: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        tick: (progress) => {
                          element.style.opacity = progress.toString();
                        },
                      }),
                      out: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        tick: (progress) => {
                          element.style.opacity = progress.toString();
                        },
                      }),
                    })}
                    class="w-[100px] h-[100px] rounded-full bg-gradient-to-br from-red-400 to-red-500"
                  />
                )}
              </div>
              <p class="font-semibold text-gray-100 text-base">Fade</p>
            </div>

            {/* Scale + Rotate */}
            <div class="flex flex-col items-center gap-4">
              <div class="w-[120px] h-[120px] flex items-center justify-center">
                {showShapes() && (
                  <div
                    ref={transition({
                      key: "scale-rotate",
                      in: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        css: (progress) => ({
                          transform: `scale(${progress}) rotate(${progress * 360}deg)`,
                          opacity: progress.toString(),
                        }),
                      }),
                      out: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        css: (progress) => ({
                          transform: `scale(${progress}) rotate(${progress * 360}deg)`,
                          opacity: progress.toString(),
                        }),
                      }),
                    })}
                    class="w-[100px] h-[100px]"
                    style={{
                      width: 0,
                      height: 0,
                      "border-left": "50px solid transparent",
                      "border-right": "50px solid transparent",
                      "border-bottom": "100px solid #4ecdc4",
                      background: "transparent",
                    }}
                  />
                )}
              </div>
              <p class="font-semibold text-gray-100 text-base">
                Scale + Rotate
              </p>
            </div>

            {/* Slide In */}
            <div class="flex flex-col items-center gap-4">
              <div class="w-[120px] h-[120px] flex items-center justify-center">
                {showShapes() && (
                  <div
                    ref={transition({
                      key: "slide-in",
                      in: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        css: (progress) => ({
                          transform: `translateX(${(1 - progress) * -100}px)`,
                          opacity: progress.toString(),
                        }),
                      }),
                      out: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        css: (progress) => ({
                          transform: `translateX(${(1 - progress) * -100}px)`,
                          opacity: progress.toString(),
                        }),
                      }),
                    })}
                    class="w-[100px] h-[100px] bg-gradient-to-br from-cyan-400 to-cyan-600 rounded-lg"
                  />
                )}
              </div>
              <p class="font-semibold text-gray-100 text-base">Slide In</p>
            </div>

            {/* Bounce Scale */}
            <div class="flex flex-col items-center gap-4">
              <div class="w-[120px] h-[120px] flex items-center justify-center">
                {showShapes() && (
                  <div
                    ref={transition({
                      key: "bounce-scale",
                      in: (element) => ({
                        spring: {
                          stiffness: stiffness() * 0.8,
                          damping: damping() * 0.7,
                        },
                        tick: (progress) => {
                          const scale = 0.5 + progress * 0.5;
                          element.style.transform = `scale(${scale})`;
                          element.style.opacity = progress.toString();
                        },
                      }),
                      out: (element) => ({
                        spring: { stiffness: stiffness(), damping: damping() },
                        tick: (progress) => {
                          const scale = 0.5 + progress * 0.5;
                          element.style.transform = `scale(${scale})`;
                          element.style.opacity = progress.toString();
                        },
                      }),
                    })}
                    class="w-[100px] h-[95px] bg-gradient-to-br from-yellow-300 to-orange-400"
                    style={{
                      "clip-path":
                        "polygon(50% 0%, 100% 38%, 82% 100%, 18% 100%, 0% 38%)",
                    }}
                  />
                )}
              </div>
              <p class="font-semibold text-gray-100 text-base">Bounce Scale</p>
            </div>
          </div>
        </div>

        {/* TransitionScope Demo Section */}
        <div class="p-8 bg-neutral-800 rounded-xl shadow-lg mt-8">
          <h2 class="text-3xl font-semibold mb-8 text-gray-100 border-b-2 border-neutral-600 pb-2">
            TransitionScope Demo
          </h2>
          <p class="text-gray-400 mb-6 leading-relaxed">
            <strong class="text-gray-200">Local scope:</strong> Skip animation
            when mounting/unmounting with parent scope.
            <br />
            <strong class="text-gray-200">Global scope (default):</strong>{" "}
            Always run animation.
          </p>

          <div class="flex flex-wrap gap-2 mb-6 justify-center">
            <button
              class="px-6 py-3 text-white border-none rounded-lg font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 shadow-lg"
              style={{
                background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
              }}
              onClick={() => setShowScopeContainer(!showScopeContainer())}
            >
              {showScopeContainer()
                ? "Hide Scope Container"
                : "Show Scope Container"}
            </button>
            <button
              class="px-6 py-3 text-white border-none rounded-lg font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
              style={{
                background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
              }}
              onClick={() => setShowLocalChild(!showLocalChild())}
              disabled={!showScopeContainer()}
            >
              {showLocalChild() ? "Hide Local Child" : "Show Local Child"}
            </button>
            <button
              class="px-6 py-3 text-white border-none rounded-lg font-semibold cursor-pointer transition-all duration-200 hover:-translate-y-0.5 shadow-lg disabled:opacity-50 disabled:cursor-not-allowed"
              style={{
                background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
              }}
              onClick={() => setShowGlobalChild(!showGlobalChild())}
              disabled={!showScopeContainer()}
            >
              {showGlobalChild() ? "Hide Global Child" : "Show Global Child"}
            </button>
          </div>

          <div class="flex gap-8 justify-center min-h-[200px] items-center">
            {showScopeContainer() && (
              <TransitionScope>
                <div class="p-8 border-2 border-dashed border-neutral-600 rounded-xl flex gap-6 bg-neutral-700/50">
                  <div class="text-center">
                    <p class="mb-2 font-semibold text-gray-200">Local Scope</p>
                    {showLocalChild() && (
                      <div
                        ref={transition({
                          key: "scope-local-child",
                          scope: "local",
                          in: () => ({
                            spring: { stiffness: 300, damping: 25 },
                            css: (progress) => ({
                              opacity: progress.toString(),
                              transform: `scale(${0.5 + progress * 0.5})`,
                            }),
                          }),
                          out: () => ({
                            spring: { stiffness: 300, damping: 25 },
                            css: (progress) => ({
                              opacity: progress.toString(),
                              transform: `scale(${0.5 + progress * 0.5})`,
                            }),
                          }),
                        })}
                        class="w-20 h-20 rounded-xl"
                        style={{
                          background:
                            "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
                        }}
                      />
                    )}
                    <p class="text-xs text-gray-500 mt-2">
                      Skips when scope unmounts
                    </p>
                  </div>

                  <div class="text-center">
                    <p class="mb-2 font-semibold text-gray-200">Global Scope</p>
                    {showGlobalChild() && (
                      <div
                        ref={transition({
                          key: "scope-global-child",
                          // scope: "global" is default
                          in: () => ({
                            spring: { stiffness: 300, damping: 25 },
                            css: (progress) => ({
                              opacity: progress.toString(),
                              transform: `scale(${0.5 + progress * 0.5})`,
                            }),
                          }),
                          out: () => ({
                            spring: { stiffness: 300, damping: 25 },
                            css: (progress) => ({
                              opacity: progress.toString(),
                              transform: `scale(${0.5 + progress * 0.5})`,
                            }),
                          }),
                        })}
                        class="w-20 h-20 rounded-xl"
                        style={{
                          background:
                            "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
                        }}
                      />
                    )}
                    <p class="text-xs text-gray-500 mt-2">Always animates</p>
                  </div>
                </div>
              </TransitionScope>
            )}
          </div>

          <div class="mt-6 p-4 bg-neutral-700/50 rounded-lg text-sm text-gray-400">
            <strong class="text-gray-200">Test scenarios:</strong>
            <ul class="mt-2 ml-6 list-disc leading-loose">
              <li>
                <strong class="text-gray-300">
                  Toggle individual children:
                </strong>{" "}
                Both should animate (scope is stable)
              </li>
              <li>
                <strong class="text-gray-300">Toggle Scope Container:</strong>{" "}
                Local child should NOT animate, Global child should animate
              </li>
            </ul>
          </div>
        </div>
      </div>
    </SsgoiTransition>
  );
}

// apps/svelte-demo/src/routes/+page.svelte
<script lang="ts">
  import { SsgoiTransition, transition, TransitionScope } from "@ssgoi/svelte";

  let showShapes = $state(true);
  let stiffness = $state(300);
  let damping = $state(30);

  // TransitionScope demo states
  let showScopeContainer = $state(true);
  let showLocalChild = $state(true);
  let showGlobalChild = $state(true);

  const colors = [
    { id: 1, color: "#FF6B6B", name: "Coral" },
    { id: 2, color: "#4ECDC4", name: "Turquoise" },
    { id: 3, color: "#45B7D1", name: "Sky Blue" },
    { id: 4, color: "#96CEB4", name: "Sage" },
    { id: 5, color: "#FECA57", name: "Sunflower" },
    { id: 6, color: "#DDA0DD", name: "Plum" },
  ];
</script>

<SsgoiTransition id="/">
  <div class="app-container">
    <div class="hero-section">
      <h1 class="app-title">SSGOI Svelte Demo</h1>
    </div>

    <!-- Hero Transition Section -->
    <div class="hero-transition-section">
      <h2 class="section-title">Hero Transition</h2>
      <div class="color-grid">
        {#each colors as item}
          <a
            href={`/item/${item.id}`}
            class="color-box"
            style="background-color: {item.color}"
            data-hero-key={`color-${item.id}`}
          >
            <span class="color-name">{item.name}</span>
          </a>
        {/each}
      </div>

      <!-- Jaemin Demo -->
      <div style="margin-top: 2rem;">
        <h3 style="font-size: 1.5rem; margin-bottom: 1rem; color: #333;">
          Jaemin Transition
        </h3>
        <a
          href="/jaemin"
          style="
            display: inline-block;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 1rem 2rem;
            border-radius: 8px;
            text-decoration: none;
            font-weight: 600;
            font-size: 1.1rem;
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
            transition: transform 0.2s ease;
          "
          onmouseenter={(e) => {
            e.currentTarget.style.transform = "translateY(-2px)";
          }}
          onmouseleave={(e) => {
            e.currentTarget.style.transform = "translateY(0)";
          }}
        >
          🎯 Demo Tunnel Emergence Animation
        </a>
      </div>
    </div>

    <!-- DOM Transition Section -->
    <div class="controls-section">
      <div class="controls">
        <div class="speed-buttons">
          <button
            class="speed-button {stiffness === 100 ? 'active' : ''}"
            onclick={() => {
              stiffness = 100;
              damping = 20;
            }}
          >
            Smooth
          </button>
          <button
            class="speed-button {stiffness === 300 ? 'active' : ''}"
            onclick={() => {
              stiffness = 300;
              damping = 30;
            }}
          >
            Normal
          </button>
          <button
            class="speed-button {stiffness === 500 ? 'active' : ''}"
            onclick={() => {
              stiffness = 500;
              damping = 40;
            }}
          >
            Fast
          </button>
        </div>

        <div class="control-group">
          <!-- svelte-ignore a11y_label_has_associated_control -->
          <label class="control-label">Stiffness</label>
          <input
            type="number"
            class="control-input"
            bind:value={stiffness}
            min="1"
            max="1000"
          />
          <span class="control-value">(1-1000)</span>
        </div>

        <div class="control-group">
          <!-- svelte-ignore a11y_label_has_associated_control -->
          <label class="control-label">Damping</label>
          <input
            type="number"
            class="control-input"
            bind:value={damping}
            min="0"
            max="100"
          />
          <span class="control-value">(0-100)</span>
        </div>
      </div>
    </div>

    <div class="toggle-section">
      <button onclick={() => (showShapes = !showShapes)} class="toggle-button">
        {showShapes ? "Hide Elements" : "Show Elements"}
      </button>
    </div>

    <div class="examples-section">
      <h2 class="section-title">DOM Transition</h2>
      <div class="shapes-grid">
        <div class="shape-container">
          <div class="shape-wrapper">
            {#if showShapes}
              <div
                use:transition={{
                  in: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.opacity = progress.toString();
                    },
                  }),
                  out: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.opacity = progress.toString();
                    },
                  }),
                }}
                class="shape circle"
              ></div>
            {/if}
          </div>
          <p class="shape-label">Fade</p>
        </div>

        <div class="shape-container">
          <div class="shape-wrapper">
            {#if showShapes}
              <div
                use:transition={{
                  in: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.transform = `scale(${progress}) rotate(${progress * 360}deg)`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                  out: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.transform = `scale(${progress}) rotate(${progress * 360}deg)`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                }}
                class="shape triangle"
              ></div>
            {/if}
          </div>
          <p class="shape-label">Scale + Rotate</p>
        </div>

        <div class="shape-container">
          <div class="shape-wrapper">
            {#if showShapes}
              <div
                use:transition={{
                  in: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.transform = `translateX(${
                        (1 - progress) * -100
                      }px)`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                  out: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      element.style.transform = `translateX(${
                        (1 - progress) * -100
                      }px)`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                }}
                class="shape square"
              ></div>
            {/if}
          </div>
          <p class="shape-label">Slide In</p>
        </div>

        <div class="shape-container">
          <div class="shape-wrapper">
            {#if showShapes}
              <div
                use:transition={{
                  in: (element) => ({
                    spring: {
                      stiffness: stiffness * 0.8,
                      damping: damping * 0.7,
                    },
                    tick: (progress) => {
                      const scale = 0.5 + progress * 0.5;
                      element.style.transform = `scale(${scale})`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                  out: (element) => ({
                    spring: { stiffness, damping },
                    tick: (progress) => {
                      const scale = 0.5 + progress * 0.5;
                      element.style.transform = `scale(${scale})`;
                      element.style.opacity = progress.toString();
                    },
                  }),
                }}
                class="shape pentagon"
              ></div>
            {/if}
          </div>
          <p class="shape-label">Bounce Scale</p>
        </div>
      </div>
    </div>

    <!-- TransitionScope Demo Section -->
    <div class="examples-section">
      <h2 class="section-title">TransitionScope Demo</h2>
      <p
        style="color: #666; margin-bottom: 1.5rem; line-height: 1.6; text-align: center;"
      >
        <strong>Local scope:</strong> Skip animation when mounting/unmounting
        with parent scope.
        <br />
        <strong>Global scope (default):</strong> Always run animation.
      </p>

      <div
        style="display: flex; gap: 0.5rem; justify-content: center; margin-bottom: 1.5rem; flex-wrap: wrap;"
      >
        <button
          class="toggle-button"
          onclick={() => (showScopeContainer = !showScopeContainer)}
        >
          {showScopeContainer ? "Hide Scope Container" : "Show Scope Container"}
        </button>
        <button
          class="toggle-button"
          onclick={() => (showLocalChild = !showLocalChild)}
          disabled={!showScopeContainer}
          style={!showScopeContainer
            ? "opacity: 0.5; cursor: not-allowed;"
            : ""}
        >
          {showLocalChild ? "Hide Local Child" : "Show Local Child"}
        </button>
        <button
          class="toggle-button"
          onclick={() => (showGlobalChild = !showGlobalChild)}
          disabled={!showScopeContainer}
          style={!showScopeContainer
            ? "opacity: 0.5; cursor: not-allowed;"
            : ""}
        >
          {showGlobalChild ? "Hide Global Child" : "Show Global Child"}
        </button>
      </div>

      <div
        style="display: flex; gap: 2rem; justify-content: center; min-height: 200px; align-items: center;"
      >
        {#if showScopeContainer}
          <TransitionScope>
            <div
              style="padding: 2rem; border: 2px dashed #ccc; border-radius: 12px; display: flex; gap: 1.5rem; background: #fafafa;"
            >
              <div style="text-align: center;">
                <p
                  style="margin-bottom: 0.5rem; font-weight: 600; color: #333;"
                >
                  Local Scope
                </p>
                {#if showLocalChild}
                  <div
                    use:transition={{
                      scope: "local",
                      in: (element) => ({
                        spring: { stiffness: 300, damping: 25 },
                        css: (progress) => ({
                          opacity: progress,
                          transform: `scale(${0.5 + progress * 0.5})`,
                        }),
                      }),
                      out: (element) => ({
                        spring: { stiffness: 300, damping: 25 },
                        css: (progress) => ({
                          opacity: progress,
                          transform: `scale(${0.5 + progress * 0.5})`,
                        }),
                      }),
                    }}
                    style="width: 80px; height: 80px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 12px;"
                  ></div>
                {/if}
                <p style="font-size: 0.75rem; color: #888; margin-top: 0.5rem;">
                  Skips when scope unmounts
                </p>
              </div>

              <div style="text-align: center;">
                <p
                  style="margin-bottom: 0.5rem; font-weight: 600; color: #333;"
                >
                  Global Scope
                </p>
                {#if showGlobalChild}
                  <div
                    use:transition={{
                      in: (element) => ({
                        spring: { stiffness: 300, damping: 25 },
                        css: (progress) => ({
                          opacity: progress,
                          transform: `scale(${0.5 + progress * 0.5})`,
                        }),
                      }),
                      out: (element) => ({
                        spring: { stiffness: 300, damping: 25 },
                        css: (progress) => ({
                          opacity: progress,
                          transform: `scale(${0.5 + progress * 0.5})`,
                        }),
                      }),
                    }}
                    style="width: 80px; height: 80px; background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%); border-radius: 12px;"
                  ></div>
                {/if}
                <p style="font-size: 0.75rem; color: #888; margin-top: 0.5rem;">
                  Always animates
                </p>
              </div>
            </div>
          </TransitionScope>
        {/if}
      </div>

      <div
        style="margin-top: 1.5rem; padding: 1rem; background: #f0f0f0; border-radius: 8px; font-size: 0.9rem; color: #555;"
      >
        <strong>Test scenarios:</strong>
        <ul style="margin: 0.5rem 0 0 1.5rem; line-height: 1.8;">
          <li>
            <strong>Toggle individual children:</strong> Both should animate (scope
            is stable)
          </li>
          <li>
            <strong>Toggle Scope Container:</strong> Local child should NOT animate,
            Global child should animate
          </li>
        </ul>
      </div>
    </div>
  </div>
</SsgoiTransition>

<style>
  .app-container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 3rem 2rem;
  }

  .hero-section {
    text-align: center;
    margin-bottom: 3rem;
  }

  .app-title {
    font-size: 3rem;
    font-weight: 700;
    margin-bottom: 0;
    letter-spacing: -0.02em;
    color: #333;
  }

  /* Controls Section */
  .controls-section {
    background: white;
    border-radius: 16px;
    padding: 2rem;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
    margin-bottom: 3rem;
  }

  .controls {
    display: flex;
    gap: 3rem;
    align-items: center;
    justify-content: center;
    flex-wrap: wrap;
  }

  .speed-buttons {
    display: flex;
    gap: 0.75rem;
  }

  .speed-button {
    padding: 0.625rem 1.25rem;
    border: 2px solid #e1e4e8;
    border-radius: 8px;
    background-color: white;
    cursor: pointer;
    font-size: 0.9rem;
    font-weight: 500;
    transition: all 0.2s;
    color: #333;
  }

  .speed-button:hover {
    border-color: #667eea;
    color: #667eea;
    transform: translateY(-1px);
  }

  .speed-button.active {
    background-color: #667eea;
    border-color: #667eea;
    color: white;
  }

  .control-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    align-items: center;
  }

  .control-label {
    font-size: 0.875rem;
    color: #666;
    font-weight: 500;
  }

  .control-input {
    width: 80px;
    padding: 0.375rem 0.75rem;
    border: 2px solid #e1e4e8;
    border-radius: 6px;
    text-align: center;
    font-size: 0.9rem;
    transition: border-color 0.2s;
  }

  .control-input:focus {
    outline: none;
    border-color: #667eea;
  }

  .control-value {
    font-size: 0.75rem;
    color: #999;
  }

  /* Toggle Button */
  .toggle-section {
    text-align: center;
    margin-bottom: 4rem;
  }

  .toggle-button {
    padding: 0.875rem 2.5rem;
    font-size: 1rem;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    border: none;
    border-radius: 10px;
    cursor: pointer;
    font-weight: 500;
    transition: all 0.3s;
    box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);
  }

  .toggle-button:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px rgba(102, 126, 234, 0.4);
  }

  /* Transition Examples Section */
  .examples-section {
    margin-bottom: 5rem;
  }

  .section-title {
    font-size: 1.5rem;
    font-weight: 600;
    margin-bottom: 2rem;
    text-align: center;
    color: #333;
  }

  .shapes-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 3rem;
    padding: 2rem;
  }

  .shape-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
    background: white;
    border-radius: 12px;
    padding: 2rem;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
    transition: all 0.3s;
  }

  .shape-container:hover {
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  }

  .shape-wrapper {
    width: 120px;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
    position: relative;
  }

  .shape {
    width: 80px;
    height: 80px;
    position: relative;
  }

  .circle {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    border-radius: 50%;
  }

  .triangle {
    width: 0;
    height: 0;
    border-left: 40px solid transparent;
    border-right: 40px solid transparent;
    border-bottom: 70px solid #4ecdc4;
  }

  .square {
    background: linear-gradient(135deg, #fa709a 0%, #fee140 100%);
    border-radius: 8px;
  }

  .pentagon {
    position: relative;
    width: 80px;
    background: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
    height: 0;
    border-left: 40px solid transparent;
    border-right: 40px solid transparent;
    border-top: 30px solid;
    border-image: linear-gradient(135deg, #f093fb 0%, #f5576c 100%) 1;
  }

  .pentagon::before {
    content: "";
    position: absolute;
    top: -70px;
    left: -40px;
    width: 0;
    height: 0;
    border-left: 40px solid transparent;
    border-right: 40px solid transparent;
    border-bottom: 40px solid #f093fb;
  }

  .shape-label {
    font-size: 1rem;
    font-weight: 500;
    color: #666;
    margin: 0;
  }

  /* Hero Transition Section */
  .hero-transition-section {
    background: white;
    border-radius: 16px;
    padding: 3rem;
    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
    margin-bottom: 3rem;
  }

  .color-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 1.5rem;
    margin-top: 2rem;
  }

  .color-box {
    aspect-ratio: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    border-radius: 12px;
    cursor: pointer;
    text-decoration: none;
    position: relative;
    overflow: hidden;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    transition: box-shadow 0.2s;
  }

  .color-box:hover {
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);
  }

  .color-name {
    color: white;
    font-size: 1.125rem;
    font-weight: 600;
    text-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  }

  @media (max-width: 768px) {
    .app-title {
      font-size: 2.5rem;
    }

    .shapes-grid {
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 2rem;
    }
  }
</style>
