// packages/qwik/src/lib/context.tsx
import { 
  createContextId, 
  useContext
} from "@builder.io/qwik";
import type { SsgoiContext, SsgoiConfig } from "./types";

export const SsgoiContextId = createContextId<{ 
  context?: SsgoiContext,
  config?: SsgoiConfig 
}>("ssgoi-context");

export const useSsgoi = () => {
  const contextStore = useContext(SsgoiContextId);
  const context = contextStore.context;
  
  if (!context) {
    throw new Error("useSsgoi must be used within a Ssgoi component");
  }
  
  return context;
};

export const SsgoiProvider = SsgoiContextId;

// packages/react/src/lib/context.tsx
import { createContext, useContext } from "react";
import type { SsgoiContext } from "./types";

const SsgoiContextInstance = createContext<SsgoiContext | null>(null);

export const SsgoiProvider = SsgoiContextInstance.Provider;

export const useSsgoi = () => {
  const context = useContext(SsgoiContextInstance);
  if (!context) {
    throw new Error("useSsgoi must be used within SsgoiProvider");
  }
  return context;
};
