// packages/solid/src/lib/ssgoi-transition.tsx
import { splitProps, type JSX, type ValidComponent } from "solid-js";
import { Dynamic } from "solid-js/web";
import { useSsgoi } from "./context";

type SsgoiTransitionProps<T extends ValidComponent = "div"> = {
  children: JSX.Element;
  id: string;
  as?: T;
  class?: string;
};

/**
 * @deprecated Set `data-ssgoi-transition` directly on the page boundary
 * element inside `<Ssgoi>` instead.
 */
export const SsgoiTransition = <T extends ValidComponent = "div">(
  props: SsgoiTransitionProps<T>,
) => {
  const [local, rest] = splitProps(props, ["children", "id", "as", "class"]);
  const ssgoi = useSsgoi();
  const component = (local.as || "div") as ValidComponent;

  return (
    <Dynamic
      component={component}
      ref={ssgoi.refFor(local.id)}
      data-ssgoi-transition={local.id}
      class={local.class}
      {...(rest as object)}
    >
      {local.children}
    </Dynamic>
  );
};

// packages/react/src/ssgoi-transition.tsx
"use client";

import type { ReactNode, ElementType } from "react";

type SsgoiTransitionProps<T extends ElementType = "div"> = {
  children: ReactNode;
  id: string;
  as?: T;
  className?: string;
};

/**
 * Marks a subtree as a Ssgoi page boundary.
 *
 * @deprecated Set `data-ssgoi-transition` directly on the page boundary
 * element inside `<Ssgoi>` instead.
 */
export const SsgoiTransition = <T extends ElementType = "div">({
  children,
  id,
  as,
  className,
  ...rest
}: SsgoiTransitionProps<T>) => {
  const Component = as || "div";
  return (
    <Component data-ssgoi-transition={id} className={className} {...rest}>
      {children}
    </Component>
  );
};
