// packages/react/src/lib/ssgoi.tsx
"use client";
import React, { useMemo } from "react";
import type { ReactNode } from "react";
import type { SsgoiConfig, SsgoiContext } from "./types";
import { SsgoiProvider } from "./context";
import { createSggoiTransitionContext } from "@ssgoi/core";

interface SsgoiProps {
  config: SsgoiConfig;
  children: ReactNode;
}

export const Ssgoi: React.FC<SsgoiProps> = ({ config, children }) => {
  const contextValue = useMemo<SsgoiContext>(
    () =>
      createSggoiTransitionContext(config, {
        // React uses MutationObserver for unmount detection,
        // so OUT and IN can arrive in any order
        outFirst: false,
      }),
    [config],
  );

  return <SsgoiProvider value={contextValue}>{children}</SsgoiProvider>;
};

// packages/solid/src/lib/ssgoi.tsx
import { createMemo, type JSX } from "solid-js";
import type { SsgoiConfig, SsgoiContext } from "./types";
import { SsgoiProvider } from "./context";
import { createSggoiTransitionContext } from "@ssgoi/core";

interface SsgoiProps {
  config: SsgoiConfig;
  children: JSX.Element;
}

export const Ssgoi = (props: SsgoiProps) => {
  const contextValue = createMemo<SsgoiContext>(() =>
    createSggoiTransitionContext(props.config, {
      // Solid uses MutationObserver for unmount detection,
      // so OUT and IN can arrive in any order
      outFirst: false,
    }),
  );

  return <SsgoiProvider value={contextValue()}>{props.children}</SsgoiProvider>;
};
