// packages/svelte/src/lib/ssgoi-transition.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { getSsgoiContext } from "./context";

  /**
   * @deprecated Set `data-ssgoi-transition` directly on the page boundary
   * element inside `<Ssgoi>` instead.
   */
  interface Props {
    id: string;
    children: Snippet;
    as?: keyof HTMLElementTagNameMap;
    class?: string;
    [key: string]: unknown;
  }

  let { id, children, as = "div", class: className, ...rest }: Props = $props();

  const ssgoi = getSsgoiContext();

  function ssgoiRef(node: HTMLElement) {
    ssgoi.refFor(id)(node);
  }
</script>

<svelte:element
  this={as}
  use:ssgoiRef
  data-ssgoi-transition={id}
  class={className}
  {...rest}
>
  {@render children()}
</svelte:element>

// packages/vue/src/lib/ssgoi-transition.vue
<script setup lang="ts">
import type { ComponentPublicInstance } from "vue";
import { useSsgoi } from "./context";

/**
 * @deprecated Set `data-ssgoi-transition` directly on the page boundary
 * element inside `<Ssgoi>` instead.
 */
interface Props {
  id: string;
  as?: keyof HTMLElementTagNameMap;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  as: "div",
  class: undefined,
});

const ssgoi = useSsgoi();

const setTransitionRef = (
  element: Element | ComponentPublicInstance | null,
) => {
  const instance = element as ComponentPublicInstance | null;
  const node = element instanceof HTMLElement ? element : instance?.$el;
  if (node instanceof HTMLElement) {
    ssgoi.value.refFor(props.id)(node);
  }
};
</script>

<template>
  <component
    :is="as"
    :ref="setTransitionRef"
    :data-ssgoi-transition="id"
    :class="props.class"
  >
    <slot />
  </component>
</template>
