// apps/docs/src/components/demo/products/index.tsx
"use client";

import React from "react";
import { products } from "./mock-data";
import { SsgoiTransition } from "@meursyphus/ssgoi-react";

export default function ProductsDemo() {
  return (
    <SsgoiTransition id="/demo/products">
      <div className="min-h-screen bg-gray-950 px-4 py-8">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Shop</h1>
          <p className="text-gray-400">Discover our curated collection</p>
        </div>

        {/* Products Grid */}
        <div className="grid grid-cols-2 gap-4">
          {products.map((product) => (
            <article
              key={product.id}
              className="bg-gray-900 rounded-xl overflow-hidden transition-all duration-200 hover:transform hover:-translate-y-1 hover:shadow-xl border border-gray-800"
            >
              {/* Product Image */}
              <div className="relative aspect-square">
                <img
                  src={product.image}
                  alt={product.name}
                  className="w-full h-full object-cover bg-gray-800"
                />
                {product.badge && (
                  <span
                    className={`absolute top-3 left-3 px-2 py-1 rounded text-xs font-semibold uppercase ${
                      product.badge === 'new'
                        ? 'bg-teal-500 text-white'
                        : product.badge === 'sale'
                        ? 'bg-red-500 text-white'
                        : 'bg-yellow-400 text-gray-900'
                    }`}
                  >
                    {product.badge}
                  </span>
                )}
              </div>

              {/* Product Info */}
              <div className="p-3 sm:p-4">
                <span className="text-xs text-gray-500 uppercase tracking-wider">
                  {product.category}
                </span>
                <h3 className="text-sm sm:text-base font-semibold text-white mt-1 mb-2 line-clamp-2">
                  {product.name}
                </h3>
                
                <p className="hidden sm:block text-xs text-gray-400 line-clamp-2 mb-3">
                  {product.description}
                </p>

                {/* Rating */}
                <div className="flex items-center gap-1 text-xs mb-3">
                  <span className="text-yellow-400">★★★★★</span>
                  <span className="font-semibold text-white">
                    {product.rating}
                  </span>
                  <span className="text-gray-500">({product.reviews})</span>
                </div>

                {/* Price Section */}
                <div className="flex justify-between items-center">
                  <div className="flex items-baseline gap-2">
                    <span className="text-lg font-bold text-white">
                      ${product.price}
                    </span>
                    {product.originalPrice && (
                      <span className="text-sm text-gray-500 line-through">
                        ${product.originalPrice}
                      </span>
                    )}
                  </div>
                  {!product.inStock && (
                    <span className="text-xs text-gray-500 font-medium">
                      Out of stock
                    </span>
                  )}
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </SsgoiTransition>
  );
}

// apps/legacy-docs/src/routes/demo/products/+page.svelte
<script lang="ts">
	import { PageTransition } from 'ssgoi';
	import type { PageData } from './$types';
	
	export let data: PageData;
</script>

<PageTransition>
	<div class="products-container">
		<h1>Shop</h1>
		<p class="subtitle">Discover our curated collection</p>
		
		<div class="products-grid">
			{#each data.products as product}
				<a href="/demo/products/{product.id}" class="product-card">
					<div data-hero-key={product.id} class="product-image">
						<img src={product.image} alt={product.name} />
						{#if product.badge}
							<span class="badge {product.badge}">{product.badge}</span>
						{/if}
					</div>
					
					<div class="product-info">
						<span class="category">{product.category}</span>
						<h3>{product.name}</h3>
						<p class="description">{product.description}</p>
						
						<div class="rating">
							<span class="stars">★★★★★</span>
							<span class="rating-value">{product.rating}</span>
							<span class="reviews">({product.reviews})</span>
						</div>
						
						<div class="price-section">
							<div class="price">
								${product.price}
								{#if product.originalPrice}
									<span class="original-price">${product.originalPrice}</span>
								{/if}
							</div>
							{#if !product.inStock}
								<span class="out-of-stock">Out of stock</span>
							{/if}
						</div>
					</div>
				</a>
			{/each}
		</div>
	</div>
</PageTransition>

<style>
	.products-container {
		padding: 2rem 0;
		padding-inline: 16px;
		min-height: calc(100vh - 200px);
		background: white;
	}

	h1 {
		font-size: 2rem;
		font-weight: 700;
		margin-bottom: 0.5rem;
	}

	.subtitle {
		color: #666;
		margin-bottom: 2rem;
	}

	.products-grid {
		display: grid;
		grid-template-columns: repeat(2, 1fr);
		gap: 1rem;
	}

	.product-card {
		display: block;
		background: white;
		border-radius: 12px;
		text-decoration: none;
		color: inherit;
		border: 1px solid #eee;
		transition: all 0.2s ease;
		position: relative;
	}

	.product-card:hover {
		transform: translateY(-2px);
		box-shadow: 0 4px 16px rgba(0, 0, 0, 0.08);
		border-color: #ddd;
	}

	.badge {
		position: absolute;
		top: 0.75rem;
		left: 0.75rem;
		padding: 0.25rem 0.5rem;
		border-radius: 4px;
		font-size: 0.7rem;
		font-weight: 600;
		text-transform: uppercase;
	}

	.badge.new {
		background: #4ECDC4;
		color: white;
	}

	.badge.sale {
		background: #FF6B6B;
		color: white;
	}

	.badge.bestseller {
		background: #FFD93D;
		color: #333;
	}

	.product-image {
		position: relative;
		width: 100%;
		aspect-ratio: 1;
		border-radius: 12px 12px 0 0;
		overflow: hidden;
	}
	
	.product-image img {
		width: 100%;
		height: 100%;
		object-fit: cover;
		background-color: #f0f0f0;
	}

	.product-info {
		padding: 1rem;
	}

	.category {
		font-size: 0.75rem;
		color: #999;
		text-transform: uppercase;
		letter-spacing: 0.5px;
	}

	.product-card h3 {
		font-size: 0.95rem;
		font-weight: 600;
		margin: 0.25rem 0 0.5rem;
		line-height: 1.2;
	}

	.description {
		display: none;
	}

	.rating {
		display: flex;
		align-items: center;
		gap: 0.25rem;
		font-size: 0.75rem;
		margin: 0.75rem 0;
	}

	.stars {
		color: #FFD700;
		letter-spacing: -2px;
	}

	.rating-value {
		font-weight: 600;
		color: #333;
	}

	.reviews {
		color: #666;
	}

	.price-section {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.price {
		font-size: 1.125rem;
		font-weight: 700;
		color: #333;
	}

	.original-price {
		font-size: 0.875rem;
		font-weight: 400;
		color: #999;
		text-decoration: line-through;
		margin-left: 0.5rem;
	}

	.out-of-stock {
		font-size: 0.75rem;
		color: #999;
		font-weight: 500;
	}

	@media (min-width: 380px) {
		.product-info {
			padding: 1.25rem;
		}

		.product-card h3 {
			font-size: 1rem;
		}

		.description {
			display: -webkit-box;
			-webkit-line-clamp: 2;
			-webkit-box-orient: vertical;
			overflow: hidden;
			font-size: 0.8rem;
			color: #666;
			line-height: 1.4;
			margin-bottom: 0.75rem;
		}
	}
</style>
