// templates/react-router/app/components/posts/index.tsx
import React from "react";
import { Link } from "react-router";
import { getAllPosts } from "./mock-data";
export default function PostsDemo() {
  const posts = getAllPosts();
  return (
    <div data-ssgoi-transition="/posts">
      <div className="min-h-full bg-[#121212] px-4 py-6">
        {/* Header */}
        <div className="mb-6">
          <h1 className="text-sm font-medium text-white mb-1">Latest Posts</h1>
          <p className="text-xs text-neutral-500">
            Insights on Svelte, Flutter, and web development
          </p>
        </div>

        {/* Posts List */}
        <div className="space-y-2">
          {posts.map((post) => (
            <Link
              key={post.id}
              to={`/posts/${post.id}`}
              className="block border border-white/5 rounded-lg overflow-hidden transition-all duration-200 hover:border-white/10"
            >
              <div className="flex gap-3 p-3">
                {/* Left: Cover Image */}
                <div className="flex-shrink-0">
                  <img
                    src={post.coverImage}
                    alt={post.title}
                    className="w-16 h-16 rounded object-cover bg-[#111]"
                  />
                </div>

                {/* Right: Content */}
                <div className="flex-1 min-w-0 flex flex-col justify-between">
                  {/* Title and excerpt */}
                  <div>
                    <h2 className="text-sm font-medium text-white mb-1 line-clamp-2">
                      {post.title}
                    </h2>
                    <p className="text-xs text-neutral-400 line-clamp-2">
                      {post.excerpt}
                    </p>
                  </div>

                  {/* Author and meta info */}
                  <div className="flex items-center gap-2 mt-1">
                    <img
                      src={post.author.avatar}
                      alt={post.author.name}
                      className="w-3 h-3 rounded-full"
                    />
                    <span className="text-xs text-neutral-500">
                      {post.author.name}
                    </span>
                    <span className="text-xs text-neutral-600">•</span>
                    <span className="text-xs text-neutral-500">
                      {post.readTime}m
                    </span>
                    <span className="text-xs px-2 py-0.5 bg-white/5 text-neutral-400 rounded ml-auto">
                      {post.category}
                    </span>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}

// templates/nuxt/pages/posts/index.vue
<template>
  <div data-ssgoi-transition="/posts">
    <div class="min-h-full bg-[#121212] px-4 py-6">
      <!-- Header -->
      <div class="mb-6">
        <h1 class="text-sm font-medium text-white mb-1">Latest Posts</h1>
        <p class="text-xs text-neutral-500">
          Insights on Svelte, Flutter, and web development
        </p>
      </div>

      <!-- Posts List -->
      <div class="space-y-2">
        <NuxtLink
          v-for="post in posts"
          :key="post.id"
          :to="`/posts/${post.id}`"
          class="block border border-white/5 rounded-lg overflow-hidden transition-all duration-200 hover:border-white/10"
        >
          <div class="flex gap-3 p-3">
            <!-- Left: Cover Image -->
            <div class="flex-shrink-0">
              <img
                :src="post.coverImage"
                :alt="post.title"
                class="w-16 h-16 rounded object-cover bg-[#111]"
              />
            </div>

            <!-- Right: Content -->
            <div class="flex-1 min-w-0 flex flex-col justify-between">
              <!-- Title and excerpt -->
              <div>
                <h2 class="text-sm font-medium text-white mb-1 line-clamp-2">
                  {{ post.title }}
                </h2>
                <p class="text-xs text-neutral-400 line-clamp-2">
                  {{ post.excerpt }}
                </p>
              </div>

              <!-- Author and meta info -->
              <div class="flex items-center gap-2 mt-1">
                <img
                  :src="post.author.avatar"
                  :alt="post.author.name"
                  class="w-3 h-3 rounded-full"
                />
                <span class="text-xs text-neutral-500">
                  {{ post.author.name }}
                </span>
                <span class="text-xs text-neutral-600">•</span>
                <span class="text-xs text-neutral-500">
                  {{ post.readTime }}m
                </span>
                <span
                  class="text-xs px-2 py-0.5 bg-white/5 text-neutral-400 rounded ml-auto"
                >
                  {{ post.category }}
                </span>
              </div>
            </div>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
const posts = useAllPosts();
</script>
