// packages/react/src/lib/context.tsx
import { createContext, useContext } from "react";
import type { SsgoiContext } from "./types";

const SsgoiContextInstance = createContext<SsgoiContext | null>(null);

export const SsgoiProvider = SsgoiContextInstance.Provider;

export const useSsgoi = () => {
  const context = useContext(SsgoiContextInstance);
  if (!context) {
    throw new Error("useSsgoi must be used within SsgoiProvider");
  }
  return context;
};

// packages/qwik/src/lib/context.ts
import { createContextId, useContext } from "@builder.io/qwik";
import type { SsgoiContext } from "./types";

export const SsgoiContextId = createContextId<SsgoiContext>("ssgoi-context");

export const useSsgoi = () => {
  const context = useContext(SsgoiContextId);
  if (!context) {
    throw new Error("useSsgoi must be used within Ssgoi component");
  }
  return context;
};
