// packages/react/src/ssgoi-transition.tsx
"use client";

import type { ReactNode, ElementType } from "react";

type SsgoiTransitionProps<T extends ElementType = "div"> = {
  children: ReactNode;
  id: string;
  as?: T;
  className?: string;
};

/**
 * Marks a subtree as a Ssgoi page boundary.
 *
 * @deprecated Set `data-ssgoi-transition` directly on the page boundary
 * element inside `<Ssgoi>` instead.
 */
export const SsgoiTransition = <T extends ElementType = "div">({
  children,
  id,
  as,
  className,
  ...rest
}: SsgoiTransitionProps<T>) => {
  const Component = as || "div";
  return (
    <Component data-ssgoi-transition={id} className={className} {...rest}>
      {children}
    </Component>
  );
};

// packages/qwik/src/lib/ssgoi-transition.tsx
import { Slot, component$ } from "@builder.io/qwik";

export interface SsgoiTransitionProps {
  id: string;
  class?: string;
}

/**
 * Marks a subtree as a Ssgoi page boundary.
 *
 * @deprecated Set `data-ssgoi-transition` directly on the page boundary
 * element inside `<Ssgoi>` instead.
 */
export const SsgoiTransition = component$<SsgoiTransitionProps>(
  ({ id, class: className }) => {
    return (
      <div data-ssgoi-transition={id} class={className}>
        <Slot />
      </div>
    );
  },
);
