// packages/react/src/lib/ssgoi-transition.tsx
"use client";

import type { ReactNode, ElementType, CSSProperties } from "react";
import { transition } from "./transition";
import { useSsgoi } from "./context";

type SsgoiTransitionProps<T extends ElementType = "div"> = {
  children: ReactNode;
  id: string;
  as?: T;
  className?: string;
  style?: CSSProperties;
};

export const SsgoiTransition = <T extends ElementType = "div">({
  children,
  id,
  as,
  className,
  style,
  ...rest
}: SsgoiTransitionProps<T>) => {
  const { getTransition, getInitialStyle } = useSsgoi();
  const Component = as || "div";
  const initialStyle = getInitialStyle(id);

  return (
    <Component
      ref={transition(getTransition(id))}
      data-ssgoi-transition={id}
      className={className}
      style={{ ...style, ...initialStyle }}
      {...rest}
    >
      {children}
    </Component>
  );
};

// packages/qwik/src/lib/ssgoi-transition.tsx
import { component$, Slot } from "@builder.io/qwik";
import { useSsgoi } from "./context";
import { transition } from "./transition";

interface SsgoiTransitionProps {
  id: string;
}

export const SsgoiTransition = component$<SsgoiTransitionProps>(({ id }) => {
  const getTransition = useSsgoi();

  return (
    <div 
      ref={transition(getTransition(id))} 
      data-ssgoi-transition={id}
    >
      <Slot />
    </div>
  );
});
