// packages/vue/src/lib/ssgoi.vue
<template>
  <div>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import type { SsgoiConfig } from "./types";
import { provideSsgoi } from "./context";
import { createSggoiTransitionContext } from "@ssgoi/core";

interface Props {
  config: SsgoiConfig;
}

const props = defineProps<Props>();

const contextValue = computed(() => createSggoiTransitionContext(props.config));

provideSsgoi(contextValue.value);
</script>

// packages/svelte/src/lib/ssgoi.svelte
<script lang="ts">
  import type { SsgoiConfig } from '@ssgoi/core/types';
  import { setSsgoiContext } from './context';
  import { createSggoiTransitionContext } from '@ssgoi/core';

  interface Props {
    config: SsgoiConfig;
    children: () => any;
  }

  let { config, children }: Props = $props();

  const contextValue = createSggoiTransitionContext(config);
  setSsgoiContext(contextValue);
</script>

{@render children()}
